#!/bin/env sh

main() {
    case "$1" in
        ('')
            bspc monitor -d  main web manual terminal media spotify temporary
            per_rule bspc_rule_remove_add
            (. /home/aleena/p/c/scmd.sh && scmd_with_bar_status global_theme_set_bspwm_startup)
        ;;
        (only-rules) per_rule bspc_rule_remove_add ;;
        (only-theme) set_bspwm_theme "$2" ;;
        (*) sed '/help stops here/q' "$0" >&2; exit 1 ;;
    esac
}

per_rule() {
    # Class (middle) is the first of the 2 WM_CLASS fields of xprop.
    # The second of the 2 WM_CLASS fields goes to the first of these.
    "$@" 'Battery widget:*:*' state=floating focus=off
    "$@"   'Clock widget:*:*' state=floating focus=off
    "$@"        'Zathura:*:*' state=tiled
    "$@"          '*:emacs:*' state=tiled
}

bspc_rule_remove_add() {
    bspc rule --remove "$1"
    bspc rule --add "$@"
}

set_bspwm_theme() {
    case "$1" in
        (autumn) bspc_configs  0  3 \#553322 \#cfaa77 mod1 true  true  true  ;;
        (glass)  bspc_configs  5  4 \#7777aa \#cc3333 mod1 true  true  true  ;;
        (hell)   bspc_configs  0 10 \#af1122 \#ffdddd mod1 true  true  true  ;;
        (round)  bspc_configs 30  5 \#7777aa \#ff3344 mod1 true  true  true  ;;
        (silent) bspc_configs  0  4 \#7777aa \#cc3333 mod1 true  true  true  ;;
        (space)  bspc_configs 50  8 \#000000 \#ccccff mod1 false true  true  ;;
        (void)   bspc_configs  0  0 \#000000 \#000000 mod1 false false false ;;
    esac
}

bspc_configs() {
    bspc config window_gap           "$1"
    bspc config border_width         "$2"
    bspc config normal_border_color  "$3"
    bspc config focused_border_color "$4"
    bspc config pointer_modifier     "$5"
    bspc config single_monocle       "$6"
    bspc config borderless_monocle   "$7"
    bspc config gapless_monocle      "$8"
}

main "$@"
