#!/bin/sh
# License at the bottom

only_this_is_called_at_the_bottom_of_this_file() {
  look_for_xresources_and_xmodmap_which_i_dont_have
  source_all_xinit_in_etc_x11
  dvorak_refresh_rate_and_brightness
  autohide_mouse_pointer
  window_effects_like_shadow
  battery_alarm
  start_pulseaudio_twice_because_of_an_odd_bug
  system_hotkeys
  become_bspwm_so_that_killing_bspwm_kills_all_these
}

look_for_xresources_and_xmodmap_which_i_dont_have() {
  xrdb -merge ~/.Xresources
  xrdb -merge /etc/X11/xinit/.Xresources 2> /dev/null
  xmodmap ~/.Xmodmap                     2> /dev/null
  xmodmap /etc/X11/xinit/.Xmodmap        2> /dev/null
}
source_all_xinit_in_etc_x11() {
  for f in /etc/X11/xinit/xinitrc.d/?*.sh
  do test -x "$f" && . "$f"
  done
}
dvorak_refresh_rate_and_brightness() {
  setxkbmap -variant dvorak
  xset -display :0.0 r rate 250 40
  xrandr --output eDP-1 --brightness 0.7
}
autohide_mouse_pointer() {
  unclutter -idle 0.7 -jitter 2 -root &
}
window_effects_like_shadow() {
  picom &
}
battery_alarm() {
  while sleep 5; do albatwid -o 50; done &
}
start_pulseaudio_twice_because_of_an_odd_bug() {
  (timeout 5s pulseaudio; pulseaudio) &  # more below
}
system_hotkeys() {
  SXHKD_SHELL=dash sxhkd &
}
become_bspwm_so_that_killing_bspwm_kills_all_these() {
  exec bspwm
}

only_this_is_called_at_the_bottom_of_this_file

# (about pulseaudio being started twice)
# A plain sleep command won't cut it.
# This started to be a problem in
# Thu Apr 13 16:56:50 EEST 2023
# when I cleaned up system's unneeded dependencies,
# along with some optional dependencies.
# The bug has to do with dbus being already in use.
# Try debugging on your own using:
# pulseaudio > /tmp/pulseaudio-1 2> /tmp/pulseaudio-2
# echo "pulseaudio closed after that" > /tmp/pulseaudio-3

# Copyright (c) 2023 Dimakopoulos Theodoros
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
