# Font configuration (changes require restart)
font:
  # The normal (roman) font face to use.
  # Style can be specified to pick a specific face.
  normal:
    # family: Iosevka
    style: Medium
    # family: "Fira Code"
    family: "Source Code Pro"
    # style: Retina

  # The bold font face
  bold:
    # family: Iosevka
    style: Bold
    # family: "Fira Code"
    family: "Source Code Pro"

  # The italic font face
  italic:
    # family: Iosevka
    style: "Light Italic"
    # style: "Light Oblique"
    # family: "Fira Code"
    family: "Source Code Pro"
    # style: "Medium Italic"

  # Point size of the font
  size: 10.0

  # Offset is the extra space around each character. offset.y can be thought of
  # as modifying the linespacing, and offset.x as modifying the letter spacing.
  offset:
    x: 0
    y: 0

  # Glyph offset determines the locations of the glyphs within their cells with
  # the default being at the bottom. Increase the x offset to move the glyph to
  # the right, increase the y offset to move the glyph upward.
  glyph_offset:
    x: 0
    y: 0

window:
  opacity: 0.95

# When true, bold text is drawn using the bright variant of colors.
draw_bold_text_with_bright_colors: false

# Use custom cursor colors. If true, display the cursor in the cursor.foreground
# and cursor.background colors, otherwise invert the colors of the cursor.
custom_cursor_colors: false

  # Colors
colors:
  # Default colors
  primary:
    background: '0x000000'
    foreground: '0x00a595'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0xbbbbbb'
    #cursor: '0xd9e5f1'

  # Normal colors
  normal:
    black:   '0x000000'
    red:     '0x9f0000'
    green:   '0x008b00'
    yellow:  '0xffcf00'
    blue:    '0x0081ff'
    magenta: '0xbc00ca'
    cyan:    '0x008b8b'
    white:   '0xbbbbbb'
  # Bright colors
  bright:
    black:   '0x545454'
    red:     '0xff0000'
    green:   '0x00ee00'
    yellow:  '0xffff00'
    blue:    '0x0000ff'
    magenta: '0xff00ff'
    cyan:    '0x00cdcd'
    white:   '0xffffff'

