#!/bin/sh

xrdb -merge ~/.Xresources
(p=/etc/X11/xinit/.Xresources ; test -r "$p" && xrdb -merge "$p")
(p=/etc/X11/xinit/.Xmodmap ; test -r "$p" && xmodmap "$p")

for f in /etc/X11/xinit/xinitrc.d/?*.sh
do test -x "$f" && . "$f"
done

xset -display :0.0 r rate 250 40

exec bspwm > ~/.cache/bspwm-log-1 2> ~/.cache/bspwm-log-2
