* Theodore's System Configuration Tour

Welcome to my iteratively hardened and compacted configuration!
You may find ~scmd.sh~, the single file command palette
and hotkey generator

#+begin_src sh
# License at the bottom
# shellcheck disable=SC2016 disable=SC1090 disable=SC2012 disable=SC2120
window_other() { bspc node next.local.leaf --focus; } #o
window_replace() { bspc node --swap "$(win_dmenu)"; }
# [...]
scmd_stands_for_system_command() { :; }
scmd_run() { c="$(dmenu < "$(this_file)" | cut -d'(' -f1)"; test "$c" && scmd_with_bar_status "$c"; } #x
# [...]
this_file() { echo ~/c/scmd.sh; }
#+end_src

the ~xinitrc~ graphical startup configuration of short shell functions

#+begin_src sh
source_system_xinit_directory() {
  for f in /etc/X11/xinit/xinitrc.d/?*.sh
  do test -x "$f" && . "$f"
  done
}

configure_x() {
  setxkbmap -variant dvorak
  xset -display :0.0 r rate 250 40
  xrandr --output eDP-1 --brightness 0.7
}
#+end_src

the POSIX ~install.sh~ that doesn't use shell arrays

#+begin_src sh
case "$1" in
    (--help|-h) echo "$0 [ARG]   where ARG one of ln, rm, --help, -h" ;;
    (ln) for_each_src_dest ln_full_path ;;
    (rm) for_each_src_dest rm_dest ;;
    ('') for_each_src_dest relink ;;
esac
#+end_src

and the two-part concatenated terminal configuration.

#+begin_src
  -rw-r--r--  1 aleena aleena   851 Jan 15 16:36 alacritty.toml
  drwxr-xr-x  2 aleena aleena 20480 Jan  6 13:06 colors
  -rw-r--r--  1 aleena aleena   283 Jan  6 12:57 head.toml
#+end_src

I used to use NeoVim. Recently I switched to Emacs.
NeoVim, TMux and ZSH were configured to be similar to the
experience of using Vi and dash without terminal multiplexing,
hense ~c/nvim/colors/desert16.vim~ and ~c/posix-shell-startup.sh~.

#+begin_src sh
PS1='$ '

alias vi=nvim
alias ls=eza
alias xc='xclip -selection clipboard'

# [...]
#+end_src

Note that I don't use Doom Emacs, I just use vanilla Emacs.
I just switch between vanilla and Doom for fun sometimes
by changing the symlinks to the configuration/cache files.
That's partly why there's no ~dot/emacs.d~.

#+begin_src sh
switch_emacs_to_vanilla() { rm ~/.emacs.d; ln -s ~/.cache/emacs/vanilla/home-emacs-dot-d/ ~/.emacs.d; }
switch_emacs_to_doom() { rm ~/.emacs.d; ln -s ~/.cache/emacs/doom/home-emacs-dot-d/ ~/.emacs.d; }
#+end_src

You may wonder how people have the TMux thing
with the list that opens a new TMux thing,
I've made one of these too.

Soon it will be time to refactor the dotfiles.
They rely on the assumption that there's a lot of them.
Don't we all make this mistake?
To think that there will be a lot of something?
I want to collect the theming related files
in one place, because ~BSPWM~, ~Picom~ and ~Alacritty~
all have themes to choose between and those need to line up.
I could just archive all the theming since I don't use it.
Also, there's no point in separating shell related
configurations in this repository since the files of
the repository will be linked in the system's directories.

Thank you for the visit and I hope this repository
can prove helpful!
