#!/bin/env sh

# Class (middle) is the first of the 2 WM_CLASS fields of xprop.
# The second of the 2 WM_CLASS fields goes to the first of these.
bspc rule --add 'Battery widget:*:*' state=floating focus=off
bspc rule --add   'Clock widget:*:*' state=floating focus=off
bspc rule --add          '*:emacs:*' state=tiled
bspc monitor eDP-1 -d m1 m2 m3 m4 m5 m6 m7

bspwm-theme glass

albatwid-alarm 50 5000 &
slock-wrapper &
unclutter --timeout 0.7 &
picom &

export SCMD_FILE=~/p/c/scmd.sh
. "$SCMD_FILE" && scmd_init
