#!/bin/sh

xrdb -merge ~/.Xresources
(p=/etc/X11/xinit/.Xresources ; test -r "$p" && xrdb -merge "$p")
(p=/etc/X11/xinit/.Xmodmap ; test -r "$p" && xmodmap "$p")

for f in /etc/X11/xinit/xinitrc.d/?*.sh
do test -x "$f" && . "$f"
done

xset -display :0.0 r rate 250 40

albatwid-alarm 50 5000              &
slock-wrapper                       &
unclutter -idle 0.7 -jitter 2 -root &
picom                               &
SXHKD_SHELL=dash sxhkd              &

exec bspwm
