#!/bin/sh
# License at the bottom

userresources=$HOME/.Xresources
#usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap
# Maybe looking for ~/.config/profile.d/11-paths.sh ?

merge_config_and_etc() {
  test -f "$sysresources" && xrdb -merge "$sysresources"
  test -f "$userresources" && xrdb -merge "$userresources"
  test -f "$sysmodmap" && xmodmap "$sysmodmap"
  test -f "$usermodmap" && xmodmap "$usermodmap"
}

source_system_xinit_directory() {
  for f in /etc/X11/xinit/xinitrc.d/?*.sh
  do test -x "$f" && . "$f"
  done
}

configure_x() {
  setxkbmap -variant dvorak
  xset -display :0.0 r rate 250 40
  xrandr --output eDP-1 --brightness 0.7
}

start_background_jobs() {
  unclutter -idle 0.7 -jitter 2 -root &  # autohide mouse pointer
  picom &
  while sleep 5; do albatwid -o 50; done &
  (timeout 5s pulseaudio; pulseaudio) &  # (*)
  SXHKD_SHELL=dash sxhkd &
}

export INTERACTIVE=no
merge_config_and_etc
source_system_xinit_directory
configure_x
start_background_jobs
exec bspwm  # perhaps also check ~/.config/bspwm/bspwmrc

# (*)
# A plain sleep command won't cut it.
# This started to be a problem in
# Thu Apr 13 16:56:50 EEST 2023
# when I cleaned up system's unneeded dependencies,
# along with some optional dependencies.
# The bug has to do with dbus being already in use.
# Try debugging on your own using:
# pulseaudio > /tmp/pulseaudio-1 2> /tmp/pulseaudio-2
# echo "pulseaudio closed after that" > /tmp/pulseaudio-3

# Copyright (c) 2023 Dimakopoulos Theodoros
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
