
[colors]
draw_bold_text_with_bright_colors = false

[colors.bright]
black = "0x4e7bbf"
blue = "0x1896c6"
cyan = "0xc8f9f3"
green = "0x9dff6e"
magenta = "0x9a5952"
red = "0xfc5e59"
white = "0xf5f4fb"
yellow = "0xefc11a"

[colors.normal]
black = "0x050404"
blue = "0x0f49c6"
cyan = "0x6fa497"
green = "0x49b117"
magenta = "0x665992"
red = "0xbc0013"
white = "0xf8dbc0"
yellow = "0xe6741d"

[colors.primary]
background = "0x1e1c44"
foreground = "0xf8dbc0"

