
[colors]
draw_bold_text_with_bright_colors = false

[colors.bright]
black = "0x3c4711"
blue = "0x00a9df"
cyan = "0x00dfc3"
green = "0x18e000"
magenta = "0x0058df"
red = "0xdf8008"
white = "0x73f990"
yellow = "0xbde000"

[colors.normal]
black = "0x112615"
blue = "0x2f697f"
cyan = "0x317f76"
green = "0x2f7e25"
magenta = "0x47577e"
red = "0x7f2b26"
white = "0x647d75"
yellow = "0x707f23"

[colors.primary]
background = "0x0f160f"
foreground = "0x637d75"

