
[colors]
draw_bold_text_with_bright_colors = false

[colors.bright]
black = "0x686868"
blue = "0x73d0ff"
cyan = "0x95e6cb"
green = "0xbae67e"
magenta = "0xd4bfff"
red = "0xf28779"
white = "0xffffff"
yellow = "0xffd580"

[colors.normal]
black = "0x191e2a"
blue = "0x6dcbfa"
cyan = "0x90e1c6"
green = "0xa6cc70"
magenta = "0xcfbafa"
red = "0xed8274"
white = "0xc7c7c7"
yellow = "0xfad07b"

[colors.primary]
background = "0x212733"
foreground = "0xd9d7ce"

