
[colors]
draw_bold_text_with_bright_colors = false

[colors.bright]
black = "0x353146"
blue = "0xffc183"
cyan = "0x2388ff"
green = "0x2dcc72"
magenta = "0xdd8d40"
red = "0xd8393d"
white = "0xe9e4ff"
yellow = "0xd8b76e"

[colors.normal]
black = "0x1f1c27"
blue = "0xffc183"
cyan = "0x2388ff"
green = "0x2dcc72"
magenta = "0xdd8d40"
red = "0xd8393d"
white = "0xb6a0ff"
yellow = "0xd8b76e"

[colors.primary]
background = "0x1f1c27"
foreground = "0xb6a0ff"

