
[colors]
draw_bold_text_with_bright_colors = false

[colors.bright]
black = "0x545753"
blue = "0x43a8ed"
cyan = "0x34e2e2"
green = "0x9aff87"
magenta = "0xff8089"
red = "0xef2828"
white = "0xededec"
yellow = "0xfffa5c"

[colors.normal]
black = "0x000000"
blue = "0x0066ff"
cyan = "0x05989a"
green = "0x1a921c"
magenta = "0xc5656b"
red = "0xcc0000"
white = "0xd3d7cf"
yellow = "0xefe43a"

[colors.primary]
background = "0x2a211c"
foreground = "0xb8a898"

