
[colors]
draw_bold_text_with_bright_colors = false

[colors.bright]
black = "0x545454"
blue = "0x589cf5"
cyan = "0x3978bb"
green = "0x34bb99"
magenta = "0xe75598"
red = "0xfa8b8e"
white = "0xffffff"
yellow = "0xffff55"

[colors.normal]
black = "0x000000"
blue = "0x589cf5"
cyan = "0x1e9ee6"
green = "0x20af89"
magenta = "0x934d95"
red = "0xf9555f"
white = "0xbbbbbb"
yellow = "0xfdf029"

[colors.primary]
background = "0x1c2836"
foreground = "0xffffff"

