
[colors]
draw_bold_text_with_bright_colors = false

[colors.bright]
black = "0x545454"
blue = "0x0000ba"
cyan = "0x54ffff"
green = "0x00ba00"
magenta = "0xff54ff"
red = "0xba0000"
white = "0xffffff"
yellow = "0xe6af00"

[colors.normal]
black = "0x000000"
blue = "0x0000a3"
cyan = "0x00baba"
green = "0x00ba00"
magenta = "0x950062"
red = "0xba0000"
white = "0xbababa"
yellow = "0xe6af00"

[colors.primary]
background = "0x12773d"
foreground = "0xfff0a4"

