
[colors]
draw_bold_text_with_bright_colors = false

[colors.bright]
black = "0x505354"
blue = "0x66d9ef"
cyan = "0xa3babf"
green = "0xbeed5f"
magenta = "0x9e6ffe"
red = "0xff669d"
white = "0xf8f8f2"
yellow = "0xe6db74"

[colors.normal]
black = "0x1b1d1e"
blue = "0x66d9ef"
cyan = "0x5e7175"
green = "0xa6e22e"
magenta = "0x9e6ffe"
red = "0xf92672"
white = "0xccccc6"
yellow = "0xfd971f"

[colors.primary]
background = "0x121212"
foreground = "0xa0a0a0"

