
[colors]
draw_bold_text_with_bright_colors = false

[colors.bright]
black = "0x615e4b"
blue = "0x9c64fe"
cyan = "0x57d1ea"
green = "0x97e023"
magenta = "0xf3005f"
red = "0xf3005f"
white = "0xf6f6ee"
yellow = "0xdfd561"

[colors.normal]
black = "0x191919"
blue = "0x9c64fe"
cyan = "0x57d1ea"
green = "0x97e023"
magenta = "0xf3005f"
red = "0xf3005f"
white = "0xc4c4b5"
yellow = "0xfa8419"

[colors.primary]
background = "0x191919"
foreground = "0xc4c4b5"

