
[colors]
draw_bold_text_with_bright_colors = false

[colors.bright]
black = "0x666666"
blue = "0x7099ec"
cyan = "0x79def1"
green = "0x66ff66"
magenta = "0xda66e5"
red = "0xff007f"
white = "0xffffff"
yellow = "0xf3d64d"

[colors.normal]
black = "0x2a2a2a"
blue = "0x396ad6"
cyan = "0x66ccff"
green = "0x78ff0e"
magenta = "0xb348bd"
red = "0xff0000"
white = "0xbababa"
yellow = "0xe6be00"

[colors.primary]
background = "0x000000"
foreground = "0xf1f1f1"

