
[colors]
draw_bold_text_with_bright_colors = false

[colors.bright]
black = "0x4a4845"
blue = "0xa1bdce"
cyan = "0xb1e7dd"
green = "0xafbea2"
magenta = "0xd7beda"
red = "0xd78787"
white = "0xefefef"
yellow = "0xe4c9af"

[colors.normal]
black = "0x2f2e2d"
blue = "0x7fa5bd"
cyan = "0x8adbb4"
green = "0x90a57d"
magenta = "0xc79ec4"
red = "0xa36666"
white = "0xd0d0d0"
yellow = "0xd7af87"

[colors.primary]
background = "0x1c1c1c"
foreground = "0xd0d0d0"

