
[colors]
draw_bold_text_with_bright_colors = false

[colors.bright]
black = "0x666c6b"
blue = "0x62b1df"
cyan = "0x64e39c"
green = "0xbfde54"
magenta = "0x5f6ede"
red = "0xdc5b5f"
white = "0xd1dfde"
yellow = "0xdeb35f"

[colors.normal]
black = "0x000000"
blue = "0x6a8fa3"
cyan = "0x6ba48f"
green = "0x99a569"
magenta = "0x6971a3"
red = "0xa16869"
white = "0x99a3a2"
yellow = "0xa29069"

[colors.primary]
background = "0x242626"
foreground = "0x99a3a2"

