
[colors]
draw_bold_text_with_bright_colors = false

[colors.bright]
black = "0x91a0b1"
blue = "0x53a4fb"
cyan = "0x83d2c0"
green = "0xaef37c"
magenta = "0xfb5ea3"
red = "0xfb695d"
white = "0x91a0b1"
yellow = "0xfc8e3e"

[colors.normal]
black = "0x4e596b"
blue = "0x9586f4"
cyan = "0x79c8b6"
green = "0x74b391"
magenta = "0xfb5ea3"
red = "0xfb695d"
white = "0xBFBFBF"
yellow = "0xfc8e3e"

[colors.primary]
background = "0x1f1f24"
foreground = "0x000000"

