
[colors]
draw_bold_text_with_bright_colors = false

[colors.bright]
black = "0x545454"
blue = "0x5485c0"
cyan = "0x58c2c0"
green = "0x88e985"
magenta = "0xbf83c0"
red = "0xec5f67"
white = "0xffffff"
yellow = "0xfdc253"

[colors.normal]
black = "0x15171c"
blue = "0x7b8fa4"
cyan = "0x7fcccb"
green = "0x91b377"
magenta = "0xa5779e"
red = "0xb14956"
white = "0xb2b8c2"
yellow = "0xc6725a"

[colors.primary]
background = "0x212121"
foreground = "0xc8c5bc"

