
[colors]
draw_bold_text_with_bright_colors = false

[colors.bright]
black = "0x1b1d21"
blue = "0x0084d4"
cyan = "0xccccff"
green = "0x56db3a"
magenta = "0xb729d9"
red = "0xdc322f"
white = "0xffffff"
yellow = "0xff8400"

[colors.normal]
black = "0x000000"
blue = "0x0084d4"
cyan = "0xccccff"
green = "0x56db3a"
magenta = "0xb729d9"
red = "0xdc322f"
white = "0xffffff"
yellow = "0xff8400"

[colors.primary]
background = "0x000000"
foreground = "0xffffff"

