
[colors]
draw_bold_text_with_bright_colors = false

[colors.bright]
black = "0x000000"
blue = "0x6699cc"
cyan = "0x66cccc"
green = "0x99cc99"
magenta = "0xcc99cc"
red = "0xf17779"
white = "0xfffefe"
yellow = "0xffcc66"

[colors.normal]
black = "0x000000"
blue = "0x6699cc"
cyan = "0x66cccc"
green = "0x99cc99"
magenta = "0xcc99cc"
red = "0xf17779"
white = "0xfffefe"
yellow = "0xffcc66"

[colors.primary]
background = "0x2c2c2c"
foreground = "0xcccccc"

