
[colors]
draw_bold_text_with_bright_colors = false

[colors.bright]
black = "0x709080"
blue = "0x5454ff"
cyan = "0x93e0e3"
green = "0x60b48a"
magenta = "0xec93d3"
red = "0xdca3a3"
white = "0xffffff"
yellow = "0xf0dfaf"

[colors.normal]
black = "0x24234f"
blue = "0x5454ff"
cyan = "0x8cd0d3"
green = "0x60b48a"
magenta = "0xf08cc3"
red = "0x705050"
white = "0x709080"
yellow = "0xdfaf8f"

[colors.primary]
background = "0x25234e"
foreground = "0xdcdccc"

