
[colors]
draw_bold_text_with_bright_colors = false

[colors.bright]
black = "0x009cc9"
blue = "0x2f8bb9"
cyan = "0xff919d"
green = "0xf4dba5"
magenta = "0xae636b"
red = "0xda6bab"
white = "0xe4838d"
yellow = "0xeac066"

[colors.normal]
black = "0x000506"
blue = "0x873bdb"
cyan = "0xc1b8b6"
green = "0x2ab250"
magenta = "0xececec"
red = "0xd94085"
white = "0xfff8dd"
yellow = "0xffd06e"

[colors.primary]
background = "0x1f1626"
foreground = "0xd9faff"

