
[colors]
draw_bold_text_with_bright_colors = false

[colors.bright]
black = "0x505050"
blue = "0x6c99ba"
cyan = "0x7dd5cf"
green = "0x7e8d50"
magenta = "0x9e4e85"
red = "0xac4142"
white = "0xf5f5f5"
yellow = "0xe5b566"

[colors.normal]
black = "0x151515"
blue = "0x6c99ba"
cyan = "0x7dd5cf"
green = "0x7e8d50"
magenta = "0x9e4e85"
red = "0xac4142"
white = "0xd0d0d0"
yellow = "0xe5b566"

[colors.primary]
background = "0x202020"
foreground = "0xd0d0d0"

