
[colors]
draw_bold_text_with_bright_colors = false

[colors.bright]
black = "0x9a6b49"
blue = "0xb8d3ed"
cyan = "0x92ced6"
green = "0x94d7ba"
magenta = "0xd09dca"
red = "0xe84526"
white = "0xfff9d4"
yellow = "0xd0d04f"

[colors.normal]
black = "0x573d25"
blue = "0x5a86ac"
cyan = "0x74a5ac"
green = "0x6ba08a"
magenta = "0xab80a6"
red = "0xbe2d26"
white = "0xdfdab7"
yellow = "0xe99c29"

[colors.primary]
background = "0x2a1e1d"
foreground = "0xdfdab7"

