
[colors]
draw_bold_text_with_bright_colors = false

[colors.bright]
black = "0x545454"
blue = "0x5555ff"
cyan = "0x55ffff"
green = "0x55ff55"
magenta = "0xff55ff"
red = "0xff5555"
white = "0xffffff"
yellow = "0xffff55"

[colors.normal]
black = "0x000000"
blue = "0xc48dff"
cyan = "0x67d9f0"
green = "0xa6e32d"
magenta = "0xfa2573"
red = "0xe52222"
white = "0xf2f2f2"
yellow = "0xfc951e"

[colors.primary]
background = "0x000000"
foreground = "0xbbbbbb"

