
[colors]
draw_bold_text_with_bright_colors = false

[colors.bright]
black = "0x545454"
blue = "0x62cae7"
cyan = "0x00ccd7"
green = "0x7df61c"
magenta = "0xff9af5"
red = "0xff5555"
white = "0xffffff"
yellow = "0xffff55"

[colors.normal]
black = "0x4c4c4c"
blue = "0x63d0f0"
cyan = "0x00d9df"
green = "0x03f622"
magenta = "0xce6fda"
red = "0xbb0000"
white = "0xbbbbbb"
yellow = "0xf2f067"

[colors.primary]
background = "0x171717"
foreground = "0xbbbbbb"

