
[colors]
draw_bold_text_with_bright_colors = false

[colors.bright]
black = "0xc4d3dc"
blue = "0x69c8ff"
cyan = "0x00e59f"
green = "0xa8ce93"
magenta = "0xd18ec2"
red = "0xef8358"
white = "0xe6eef3"
yellow = "0xe5e77f"

[colors.normal]
black = "0x8799a4"
blue = "0x83afe4"
cyan = "0x7fc1b6"
green = "0xa6cb91"
magenta = "0xd460da"
red = "0xefc08d"
white = "0xc4d3dc"
yellow = "0xd7d690"

[colors.primary]
background = "0x3c4c54"
foreground = "0x8798a3"

