
[colors]
draw_bold_text_with_bright_colors = false

[colors.bright]
black = "0x505354"
blue = "0x3f78ff"
cyan = "0x23ced4"
green = "0xb6e354"
magenta = "0x9e6ffe"
red = "0xff5995"
white = "0xf8f8f2"
yellow = "0xfeed6c"

[colors.normal]
black = "0x1b1d1e"
blue = "0x2656d6"
cyan = "0x37c8b4"
green = "0x4df740"
magenta = "0x8c54fe"
red = "0xf92672"
white = "0xccccc6"
yellow = "0xf3fd21"

[colors.primary]
background = "0x1b1d1e"
foreground = "0xf8f8f8"

