
[colors]
draw_bold_text_with_bright_colors = false

[colors.bright]
black = "0x545454"
blue = "0x1200f8"
cyan = "0x8ae9fc"
green = "0x50fa7b"
magenta = "0xff78c5"
red = "0xff5454"
white = "0xffffff"
yellow = "0xf0fa8b"

[colors.normal]
black = "0x000000"
blue = "0x3282ff"
cyan = "0x0037fc"
green = "0xfa0074"
magenta = "0x1b3cff"
red = "0xff5555"
white = "0xbbbbbb"
yellow = "0x7f0a1f"

[colors.primary]
background = "0x222330"
foreground = "0xcef3ff"

