
[colors]
draw_bold_text_with_bright_colors = false

[colors.bright]
black = "0x191919"
blue = "0x75d4ff"
cyan = "0x6cbeb5"
green = "0xb6e875"
magenta = "0xb975e6"
red = "0xff355b"
white = "0xc1c8d6"
yellow = "0xffc150"

[colors.normal]
black = "0x191919"
blue = "0x75d3ff"
cyan = "0x6cbeb5"
green = "0xb6e875"
magenta = "0xb975e6"
red = "0xff355b"
white = "0xc1c8d6"
yellow = "0xffc150"

[colors.primary]
background = "0x191919"
foreground = "0xb2c8d6"

