
[colors]
draw_bold_text_with_bright_colors = false

[colors.bright]
black = "0x393e48"
blue = "0x61afef"
cyan = "0x56b6c2"
green = "0x56b6c2"
magenta = "0xbe5046"
red = "0xd19a66"
white = "0xabb2bf"
yellow = "0xe5c07b"

[colors.normal]
black = "0x282c34"
blue = "0x61afef"
cyan = "0x56b6c2"
green = "0x98c379"
magenta = "0xbe5046"
red = "0xe06c75"
white = "0x979eab"
yellow = "0xe5c07b"

[colors.primary]
background = "0x282c34"
foreground = "0x979eab"

