
[colors]
draw_bold_text_with_bright_colors = false

[colors.bright]
black = "0x545753"
blue = "0x719ecf"
cyan = "0x34e2e2"
green = "0x8ae234"
magenta = "0xad7ea7"
red = "0xef2828"
white = "0xededec"
yellow = "0xfce94e"

[colors.normal]
black = "0x000000"
blue = "0x3464a4"
cyan = "0x05989a"
green = "0x4e9a05"
magenta = "0x74507a"
red = "0xcc0000"
white = "0xd3d7cf"
yellow = "0xc4a000"

[colors.primary]
background = "0xffffff"
foreground = "0x000000"

