
[colors]
draw_bold_text_with_bright_colors = false

[colors.bright]
black = "0x5c3125"
blue = "0x8579ed"
cyan = "0xeaeaea"
green = "0x28e51f"
magenta = "0xa05dee"
red = "0xff6387"
white = "0xbfa3ff"
yellow = "0xf08061"

[colors.normal]
black = "0x000000"
blue = "0x554d9a"
cyan = "0x808080"
green = "0x37a315"
magenta = "0x6c3ba1"
red = "0xaf425b"
white = "0x87799c"
yellow = "0xac5b41"

[colors.primary]
background = "0x1b1b23"
foreground = "0x86799a"

