
[colors]
draw_bold_text_with_bright_colors = false

[colors.bright]
black = "0xfff688"
blue = "0x3c7dd2"
cyan = "0x6cbc67"
green = "0x8ff586"
magenta = "0x8230a7"
red = "0xd4312e"
white = "0x8ff586"
yellow = "0xe9f06d"

[colors.normal]
black = "0x142630"
blue = "0x8ff586"
cyan = "0x8ff586"
green = "0x3aa5ff"
magenta = "0x781aa0"
red = "0xff2320"
white = "0xba45b1"
yellow = "0xe9e75c"

[colors.primary]
background = "0x142838"
foreground = "0x8ff586"

