
[colors]
draw_bold_text_with_bright_colors = false

[colors.bright]
black = "0x545454"
blue = "0x5555ff"
cyan = "0x55ffff"
green = "0x55ff55"
magenta = "0xff55ff"
red = "0xff5555"
white = "0xffffff"
yellow = "0xffff55"

[colors.normal]
black = "0x4c4c4c"
blue = "0x266ad7"
cyan = "0x00d9df"
green = "0x5ede8f"
magenta = "0xbb00bb"
red = "0xbb0000"
white = "0xbbbbbb"
yellow = "0xf2f067"

[colors.primary]
background = "0x000000"
foreground = "0xbbbbbb"

