
[colors]
draw_bold_text_with_bright_colors = false

[colors.bright]
black = "0x7f7f7f"
blue = "0x0000cc"
cyan = "0x0086cb"
green = "0x009600"
magenta = "0xcc00cc"
red = "0xcc0000"
white = "0xffffff"
yellow = "0xd06b00"

[colors.normal]
black = "0x000000"
blue = "0x0000cc"
cyan = "0x0087cc"
green = "0x009600"
magenta = "0xcc00cc"
red = "0xcc0000"
white = "0xcccccc"
yellow = "0xd06b00"

[colors.primary]
background = "0xdfdbc3"
foreground = "0x3b2322"

