
[colors]
draw_bold_text_with_bright_colors = false

[colors.bright]
black = "0x262626"
blue = "0x65a9f0"
cyan = "0xb7dfdd"
green = "0xaff08b"
magenta = "0xddb7df"
red = "0xe02453"
white = "0xffffff"
yellow = "0xdfddb7"

[colors.normal]
black = "0x000000"
blue = "0x479bed"
cyan = "0x6bbeb8"
green = "0x71be6b"
magenta = "0xe878d6"
red = "0xd52e4d"
white = "0xd6d6d6"
yellow = "0xbeb86b"

[colors.primary]
background = "0x762423"
foreground = "0xffffff"

