
[colors]
draw_bold_text_with_bright_colors = false

[colors.bright]
black = "0x326889"
blue = "0x33a5d9"
cyan = "0x41c3ad"
green = "0x30cf7b"
magenta = "0xad6bdc"
red = "0xdd5943"
white = "0xd4d4d4"
yellow = "0xe7d74b"

[colors.normal]
black = "0x2c3f57"
blue = "0x325d96"
cyan = "0x35a08f"
green = "0x199171"
magenta = "0x8a5ddb"
red = "0xbe2d26"
white = "0x23d082"
yellow = "0xda8e26"

[colors.primary]
background = "0x23364a"
foreground = "0x30cf7b"

