
[colors]
draw_bold_text_with_bright_colors = false

[colors.bright]
black = "0x3d3d3d"
blue = "0x477ab3"
cyan = "0x6096bf"
green = "0x53a6a6"
magenta = "0x7e62b3"
red = "0xbf4d80"
white = "0xc0c0c0"
yellow = "0x9e9ecb"

[colors.normal]
black = "0x333333"
blue = "0x395573"
cyan = "0x31658c"
green = "0x287373"
magenta = "0x5e468c"
red = "0x8c4665"
white = "0x899ca1"
yellow = "0x7c7c99"

[colors.primary]
background = "0x101010"
foreground = "0x999993"

